"a: dependencies":
  - changed-files:
      - any-glob-to-any-file: "uv.lock"

"a: devops":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/dependabot.yml"
          - ".github/labeler.yml"
          - ".pre-commit-config.yaml"

"a: documentation":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**"
          - "**.md"
          - "mkdocs.yml"
