site_name: MCPROTO
site_url: https://py-mine.github.io/mcproto
copyright: Mcproto Documentation &copy; 2024 by <a href="mailto:itsdrike@protonmail.com">ItsDrike</a>

repo_url: https://github.com/py-mine/mcproto
repo_name: py-mine/mcproto

watch:
  [LICENSE.txt, LICENSE-THIRD-PARTY.txt, ATTRIBUTION.md, SECURITY.md, CHANGELOG.md, changes]

exclude_docs: |
  LICENSE.md

nav:
  - Home: index.md
  - Installation:
      - Installation: installation/index.md
      - Versioning Model: installation/versioning-model.md
      - Changelog: installation/changelog.md
  - Usage:
      - usage/index.md
      - First steps: usage/first-steps.md
      - Packet Communication: usage/packet-communication.md
      - Authentication: usage/authentication.md
  - FAQ: faq.md
  - Community:
      - Code of Conduct: community/code-of-conduct.md
      - Attributions: community/attribution.md
      - License: community/license.md
      - Contributing:
          - Reporting a bug: contributing/reporting-a-bug.md
          - Asking a question: https://github.com/py-mine/mcproto/discussions
          - Making a pull request: contributing/making-a-pr.md
          - Security Policy: contributing/security-policy.md
      - Guides:
          - contributing/guides/index.md
          - Setting things up: contributing/guides/setup.md
          - Style Guide: contributing/guides/style-guide.md
          - Docstring formatting: contributing/guides/docstrings.md
          - Type hinting: contributing/guides/type-hints.md
          - Slotscheck: contributing/guides/slotscheck.md
          - Pre-commit: contributing/guides/precommit.md
          - Changelog: contributing/guides/changelog.md
          - Breaking Changes: contributing/guides/breaking-changes.md
          - Unit Tests: contributing/guides/unit-tests.md
          - Documentation: contributing/guides/documentation.md
          - Great commits: contributing/guides/great-commits.md
  - API Reference:
      - Protocol: reference/public/protocol.md
      - Authentication: reference/public/authentication.md
      - Encryption: reference/public/encryption.md
      - Multiplayer: reference/public/multiplayer.md
      - Types: reference/public/types.md
      - Packets: reference/public/packets.md
  - Private API Reference:
      - reference/private/index.md
      - ABCs: reference/private/abc.md
      - Deprecation: reference/private/deprecation.md
      - Authentication: reference/private/authentication.md
      - Protocol: reference/private/protocol.md
      - Types: reference/private/types.md
      - Packets: reference/private/packets.md

theme:
  name: material
  logo: assets/py-mine_logo.png
  palette:
    - media: "(prefers-color-scheme)"
      primary: black
      accent: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.share
    - search.suggest
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow

extra_css:
  - css/mkdocstrings.css
  - css/material.css
  - css/admoditions.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - markdown-exec:
      ansi: required
  - mike:
      canonical_version: "latest"
      version_selector: true
  - mkdocstrings:
      enable_inventory: true
      default_handler: python
      handlers:
        python:
          options:
            docstring_options:
              ignore_init_summary: true
            show_root_heading: false
            show_root_toc_entry: false
            show_source: false
            docstring_style: sphinx
            relative_crossrefs: true
            scoped_crossrefs: true
            show_signature_annotations: true
            signature_crossrefs: true
            separate_signature: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            parameter_headings: true
            show_object_full_path: true
            docstring_section_style: table
          import:
            - url: https://docs.python.org/3.13/objects.inv
              domains: [std, py]
            - https://typing-extensions.readthedocs.io/en/latest/objects.inv
            - https://cryptography.io/en/stable/objects.inv
            - https://python-semanticversion.readthedocs.io/en/stable/objects.inv

extra:
  version:
    provider: mike
    default: latest
    alias: true
