site_name: MCPROTO
site_url: https://py-mine.github.io/mcproto

repo_url: https://github.com/py-mine/mcproto
repo_name: py-mine/mcproto

watch:
  [LICENSE.txt, LICENSE-THIRD-PARTY.txt, ATTRIBUTION.md, CHANGELOG.md, changes]

exclude_docs: |
  LICENSE.md

nav:
  - Home: index.md
  - Installation:
      - Installation: installation/index.md
      - Version Guarantees: installation/version-guarantees.md
      - Changelog: installation/changelog.md
  - Community:
      - Code of Conduct: community/code-of-conduct.md
      - Attributions: community/attribution.md
      - License: community/license.md
      - Contributing:
          - Reporting a bug: contributing/reporting-a-bug.md
          - Asking a question: https://github.com/py-mine/mcproto/discussions
          - Making a pull request: contributing/making-a-pr.md
      - Guides:
          - contributing/guides/index.md
          - Setting things up: contributing/guides/setup.md
          - Style Guide: contributing/guides/style-guide.md
          - Docstring formatting: contributing/guides/docstrings.md
          - Type hinting: contributing/guides/type-hints.md
          - Pre-commit: contributing/guides/precommit.md
          - Other tools: contributing/guides/other-tools.md
          - Changelog: contributing/guides/changelog.md
          - Great commits: contributing/guides/great-commits.md
          - Unit Tests: contributing/guides/unit-tests.md
          - Deprecations: contributing/guides/deprecations.md

theme:
  name: material
  logo: assets/py-mine_logo.png
  palette:
    - media: "(prefers-color-scheme)"
      primary: black
      accent: black
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  features:
    - content.tabs.link
    - content.code.copy
    - content.action.edit
    - search.highlight
    - search.share
    - search.suggest
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - markdown-exec:
      ansi: required
  - mike:
      canonical_version: "latest"
      version_selector: true

extra:
  version:
    provider: mike
    default: latest
    alias: true
