name: Bug report
description: Found a bug? Let us know so we can fix it!
labels: ["type: bug"]

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: Describe the bug. What's wrong?
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Reproduction
      description: Steps to reproduce the bug. This can also be a code snippet. Try to keep things as minimal as you can.
      value: |
        1.
        2.
        3.
        4.
    validations:
      required: true

  - type: input
    id: library-version
    attributes:
      label: Library version
      description: mcproto version used when this bug was encountered. (Find out with `pip show mcproto` command)
      placeholder: 0.1.0
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python version
      description: Version of python interpreter you're using. (Find out with `python -V` or `py -V`)
      placeholder: 3.11.1
    validations:
      required: true

  - type: input
    id: operating-system
    attributes:
      label: Operating system
      description: Operating system used when this bug was encountered.
      placeholder: Windows 11 / Linux - Ubuntu 22.10 / MacOS / ...

  - type: textarea
    id: further-info
    attributes:
      label: Further info
      description: Any further info such as images/videos, exception tracebacks, ...

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure to tick all the following boxes.
      options:
        - label: I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.
          required: true
        - label: I have made sure to remove ANY sensitive information (passwords, credentials, personal details, etc.).
          required: true
