name: Feature request
description: Got a cool idea you would like implemented? Share it with us!
labels: ["t: feature"]

body:
  - type: textarea
    id: problem
    attributes:
      label: Why is this needed?
      description: Why should this feature be implemented? What problem(s) would it solve?
    validations:
      required: true

  - type: textarea
    id: ideal-implementation
    attributes:
      label: Ideal implementation / solution
      description: How do you think the problem above should be solved?
      value: To be decided.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Make sure to tick all the following boxes.
      options:
        - label: I have searched the issue tracker and have made sure it's not a duplicate. If it is a follow up of another issue, I have specified it.
          required: true
