name: "Issue Labeler"

on:
  issues:
    types: [opened]

permissions:
  issues: write
  contents: read

jobs:
  issue-labeler:
    # Don't run in forks, they probably don't have the same labels set up
    if: github.repository_owner == 'py-mine'

    runs-on: ubuntu-latest
    steps:
      - name: Label issue ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue edit "$NUMBER" --add-label "s: pending"
