name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: label-the-PR
        uses: actions/labeler@v5
