name: "Pull Request Labeler"
on:
  pull_request_target:

permissions:
  contents: read

jobs:
  pr-labeler:
    # Don't run in forks, they probably don't have the same labels set up
    if: github.repository_owner == 'py-mine'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.PYMINE_BOT_APP_ID }}
          private-key: ${{ secrets.PYMINE_BOT_PRIVATE_KEY }}
          permission-contents: read
          permission-pull-requests: write

      - id: label-the-PR
        uses: actions/labeler@v5
        with:
          repo-token: ${{ steps.generate_tokens.outputs.token }}
