name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened]

jobs:
  pr-labeler:
    # Don't run in forks, they probably don't have the same labels set up
    if: github.repository_owner == 'py-mine'

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - id: label-the-PR
        uses: actions/labeler@v5
